version: '3.2'
services:
  app:
    image: quay.io/macmiranda/simple-flask:0.4
    ports:
      - "9090:9090"
    healthcheck: 
        test: ["CMD", "nc", "-z", "localhost", "9090"]
        interval: 30s
        timeout: 10s
        retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400M
      replicas: 9
#        placement:
#        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  redis:
    image: "redis:alpine"
    healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "6379"]
        interval: 30s
        timeout: 10s
        retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
      replicas: 1
#        placement:
#        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
