version: '3.2'
services:
  app:
    image: quay.io/macmiranda/simple-flask:0.3
    ports:
      - "9090:9090"
    restart: always
    healthcheck: 
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 1m
        timeout: 10s
        retries: 3
    deploy:
      replicas: 6
#        placement:
#        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:6379"]
        interval: 1m
        timeout: 10s
        retries: 3
