version: '3.2'
services:
  app:
    image: quay.io/macmiranda/simple-flask:0.3
    ports:
      - "9000-9100:9090"
#    restart: always
    healthcheck: 
        test: ["CMD", "nc", "-z", "localhost", "9090"]
        interval: 30s
        timeout: 10s
        retries: 3
    deploy:
      replicas: 2
#        placement:
#        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "6379"]
        interval: 30s
        timeout: 10s
        retries: 3
